lib/stord_assessment_web/router.ex
defmodule StordAssessmentWeb.Router do
  use StordAssessmentWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {StordAssessmentWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StordAssessmentWeb do
    pipe_through :browser

    get "/", PageController, :index

    live "/stats", UrlLive.Index, :index
    post "/csv", UrlController, :export_csv

    live "/urls", UrlLive.Index, :index
    live "/urls/new", UrlLive.Index, :new
    live "/urls/:id/edit", UrlLive.Index, :edit

    live "/urls/:id", UrlLive.Show, :show
    live "/urls/:id/show/edit", UrlLive.Show, :edit

    get "/:hash", UrlController, :redirect_to
  end

  # Other scopes may use custom stacks.
  scope "/api", StordAssessmentWeb do
    pipe_through :api

    resources "/urls", UrlController, except: [:new, :edit]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: StordAssessmentWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/stord_assessment_web/live/live_helpers.ex
defmodule StordAssessmentWeb.LiveHelpers do
  @moduledoc false
  import Phoenix.LiveView
  import Phoenix.LiveView.Helpers

  alias Phoenix.LiveView.JS

  @doc """
  Renders a live component inside a modal.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <.modal return_to={Routes.url_index_path(@socket, :index)}>
        <.live_component
          module={StordAssessmentWeb.UrlLive.FormComponent}
          id={@url.id || :new}
          title={@page_title}
          action={@live_action}
          return_to={Routes.url_index_path(@socket, :index)}
          url: @url
        />
      </.modal>
  """
  def modal(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div id="modal" class="phx-modal fade-in" phx-remove={hide_modal()}>
      <div
        id="modal-content"
        class="phx-modal-content fade-in-scale"
        phx-click-away={JS.dispatch("click", to: "#close")}
        phx-window-keydown={JS.dispatch("click", to: "#close")}
        phx-key="escape"
      >
        <%= if @return_to do %>
          <%= live_patch "✖",
            to: @return_to,
            id: "close",
            class: "phx-modal-close",
            phx_click: hide_modal()
          %>
        <% else %>
          <a id="close" href="#" class="phx-modal-close" phx-click={hide_modal()}>✖</a>
        <% end %>

        <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end

  defp hide_modal(js \\ %JS{}) do
    js
    |> JS.hide(to: "#modal", transition: "fade-out")
    |> JS.hide(to: "#modal-content", transition: "fade-out-scale")
  end
end

lib/stord_assessment_web/live/url_live/form_component.ex
defmodule StordAssessmentWeb.UrlLive.FormComponent do
  use StordAssessmentWeb, :live_component

  alias StordAssessment.UrlShortener

  @impl true
  def update(%{url: url} = assigns, socket) do
    changeset = UrlShortener.change_url(url)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"url" => url_params}, socket) do
    changeset =
      socket.assigns.url
      |> UrlShortener.change_url(url_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"url" => url_params}, socket) do
    save_url(socket, socket.assigns.action, url_params)
  end

  defp save_url(socket, :edit, url_params) do
    case UrlShortener.update_url(socket.assigns.url, url_params) do
      {:ok, _url} ->
        {:noreply,
         socket
         |> put_flash(:info, "Url updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_url(socket, :new, url_params) do
    case UrlShortener.create_url(url_params) do
      {:ok, _url} ->
        {:noreply,
         socket
         |> put_flash(:info, "Url created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/stord_assessment_web/live/url_live/index.ex
defmodule StordAssessmentWeb.UrlLive.Index do
  use StordAssessmentWeb, :live_view

  alias StordAssessment.UrlShortener
  alias StordAssessment.UrlShortener.Url

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :urls, list_urls())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Url")
    |> assign(:url, UrlShortener.get_url!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Url")
    |> assign(:url, %Url{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Urls")
    |> assign(:url, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    url = UrlShortener.get_url!(id)
    {:ok, _} = UrlShortener.delete_url(url)

    {:noreply, assign(socket, :urls, list_urls())}
  end

  defp list_urls do
    UrlShortener.list_urls()
  end
end

lib/stord_assessment_web/live/url_live/show.ex
defmodule StordAssessmentWeb.UrlLive.Show do
  use StordAssessmentWeb, :live_view

  alias StordAssessment.UrlShortener

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:url, UrlShortener.get_url!(id))}
  end

  defp page_title(:show), do: "Show Url"
  defp page_title(:edit), do: "Edit Url"
end

lib/stord_assessment_web/live/url_live/form_component.html.heex
<div>
  <h2><%= @title %></h2>

  <.form
    let={f}
    for={@changeset}
    id="url-form"
    phx-target={@myself}
    phx-change="validate"
    phx-submit="save">

    <%= label f, :url %>
    <%= text_input f, :url %>
    <%= error_tag f, :url %>

    <div>
      <%= submit "Save", phx_disable_with: "Saving..." %>
    </div>
  </.form>
</div>

lib/stord_assessment_web/live/url_live/index.html.heex
<h1>Listing Urls</h1>

<%= if @live_action in [:new, :edit] do %>
  <.modal return_to={Routes.url_index_path(@socket, :index)}>
    <.live_component
      module={StordAssessmentWeb.UrlLive.FormComponent}
      id={@url.id || :new}
      title={@page_title}
      action={@live_action}
      url={@url}
      return_to={Routes.url_index_path(@socket, :index)}
    />
  </.modal>
<% end %>

<%= link to: Routes.url_path(@socket, :export_csv), class: "button", method: :post do %>
  Export CSV
<% end %>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Hash</th>
      <th>Visits</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="urls">
    <%= for url <- @urls do %>
      <tr id={"url-#{url.id}"}>
        <td><%= live_redirect url.url, to: url.url %></td>
        <td><%= live_redirect url.hash, to: Routes.url_path(@socket, :redirect_to, url.hash) %></td>
        <td><%= url.visits %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.url_show_path(@socket, :show, url) %></span>
          <span><%= live_patch "Edit", to: Routes.url_index_path(@socket, :edit, url) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: url.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= live_patch "New Url", to: Routes.url_index_path(@socket, :new) %></span>

lib/stord_assessment_web/live/url_live/show.html.heex
<h1>Show Url</h1>

<%= if @live_action in [:edit] do %>
  <.modal return_to={Routes.url_show_path(@socket, :show, @url)}>
    <.live_component
      module={StordAssessmentWeb.UrlLive.FormComponent}
      id={@url.id}
      title={@page_title}
      action={@live_action}
      url={@url}
      return_to={Routes.url_show_path(@socket, :show, @url)}
    />
  </.modal>
<% end %>

<ul>

  <li>
    <strong>Url:</strong>
    <%= live_redirect @url.url, to: @url.url %>

  </li>

  <li>
    <strong>Hash:</strong>
    <%= live_redirect @url.hash, to: Routes.url_path(@socket, :redirect_to, @url.hash) %>
  </li>

  <li>
    <strong>Visits:</strong>
    <%= @url.visits %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.url_show_path(@socket, :edit, @url), class: "button" %></span> |
<span><%= live_redirect "Back", to: Routes.url_index_path(@socket, :index) %></span>